In [1]:
import numpy as np

In [2]:
student_marks = np.random.randint(1,101,15)
print(student_marks)

[65 89 96 79 24 34 16 37 96 68 43 75 91 49 51]


In [3]:
student_marks

array([65, 89, 96, 79, 24, 34, 16, 37, 96, 68, 43, 75, 91, 49, 51])

In [4]:
np.clip(student_marks,a_min=34,a_max=100)

array([65, 89, 96, 79, 34, 34, 34, 37, 96, 68, 43, 75, 91, 49, 51])

In [5]:
print(np.where(student_marks == 34))
print(np.where(student_marks != 34))
print(np.where(student_marks < 34))


(array([5], dtype=int64),)
(array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64),)
(array([4, 6], dtype=int64),)


In [6]:
student_marks[[1,4]].reshape(2,1)

array([[89],
       [24]])

In [7]:
from numpy.random import randint as ri

In [8]:
arr = ri(1,100,50)
print(arr)

[40 41 58 42 70 37 23 52 66 94  4  3 46 26 70 61 94 44 73  8 91 94 92 91
 30 89 62 84 34 40 10 16 41 42 74 88 39 11 49 64 15 71 84 89 38 23 27 55
 46 74]


In [9]:
arr1 = arr.reshape(5,10,1)
print(arr1)
print("MAX --> ",arr1.max())
print("MAX --> ",arr1.min())

[[[40]
  [41]
  [58]
  [42]
  [70]
  [37]
  [23]
  [52]
  [66]
  [94]]

 [[ 4]
  [ 3]
  [46]
  [26]
  [70]
  [61]
  [94]
  [44]
  [73]
  [ 8]]

 [[91]
  [94]
  [92]
  [91]
  [30]
  [89]
  [62]
  [84]
  [34]
  [40]]

 [[10]
  [16]
  [41]
  [42]
  [74]
  [88]
  [39]
  [11]
  [49]
  [64]]

 [[15]
  [71]
  [84]
  [89]
  [38]
  [23]
  [27]
  [55]
  [46]
  [74]]]
MAX -->  94
MAX -->  3


In [10]:
m = ri(1,100,20).reshape(4,5) #matrix of random integer
print("\n 4 X 5 matrix of random integer \n",'-'*50,'\n',m)
print("\n Here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(m)) # default axis=1
print("\n Here is the sorted matrix along each column \n",'-'*50,'\n',np.sort(m, axis=0))


 4 X 5 matrix of random integer 
 -------------------------------------------------- 
 [[27 63 56  7  8]
 [77 72 62 70  4]
 [54 26 21 60 15]
 [47 73 24  5 90]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[ 7  8 27 56 63]
 [ 4 62 70 72 77]
 [15 21 26 54 60]
 [ 5 24 47 73 90]]

 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[27 26 21  5  4]
 [47 63 24  7  8]
 [54 72 56 60 15]
 [77 73 62 70 90]]


### Index and slicing

In [11]:
arr = np.arange(13,30,1)
print("Array",arr)

Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [12]:
print("Element of 7th index is =",arr[7])
print("Element of 3rd index is =",arr[3])
print("Elements between 3rd and 7th index are =",arr[3:7])
print("Elements from 3rd to end are =",arr[3:])

Element of 7th index is = 20
Element of 3rd index is = 16
Elements between 3rd and 7th index are = [16 17 18 19]
Elements from 3rd to end are = [16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [13]:
mat = np.array([[1,3,5],[8,9,4],[10,2,90]])
print(mat)

[[ 1  3  5]
 [ 8  9  4]
 [10  2 90]]


In [14]:
print("Extracting a full Row --> ",mat[2])

Extracting a full Row -->  [10  2 90]


In [15]:
print("All Columns after index 1 -->\n",mat[:,1:])

All Columns after index 1 -->
 [[ 3  5]
 [ 9  4]
 [ 2 90]]


In [16]:
print("\nSubsetting Sub-Matrix\n"+'--'*12)

print("Submatrix Subsetting --> Matrix between row index 1 and 2 & column index 1 & 2, the middle most element of this 3X3 2D matrix\n",mat[1:2,1:2])


Subsetting Sub-Matrix
------------------------
Submatrix Subsetting --> Matrix between row index 1 and 2 & column index 1 & 2, the middle most element of this 3X3 2D matrix
 [[9]]


In [17]:
print(mat[0:1,0:2])

[[1 3]]


In [18]:
# Update Matrix
mat_2 = np.array([[1,2,3],[2,6,30],[90,543,90]])
print("Original Matrix --> \n",mat_2)
mat_2[1,2] = 60
print("Updated Matrix --> \n",mat_2)

Original Matrix --> 
 [[  1   2   3]
 [  2   6  30]
 [ 90 543  90]]
Updated Matrix --> 
 [[  1   2   3]
 [  2   6  60]
 [ 90 543  90]]


In [19]:
mat_3 = np.array(ri(10,100,25)).reshape(5,5)
print('Matrix of random 2 digit numbers \n------------\n',mat_3)

Matrix of random 2 digit numbers 
------------
 [[67 28 31 87 56]
 [28 65 97 11 86]
 [82 69 96 68 26]
 [52 41 92 40 43]
 [28 22 15 90 17]]


In [20]:
print("Elements greater than 20\n ",mat_3[mat_3>20])

Elements greater than 20
  [67 28 31 87 56 28 65 97 86 82 69 96 68 26 52 41 92 40 43 28 22 90]


In [21]:
print(np.where(mat_3 == 66)) # It returns the row index first, then column index of particular element

(array([], dtype=int64), array([], dtype=int64))


In [22]:
age = 50
np.where(age>60,'Retired','Still Working')

array('Still Working', dtype='<U13')

### UNIVERSAL FUNCTIONS

In [23]:
mat_4 = 6*np.ones(50).reshape(10,5)
mat_5 = 5*np.ones(50).reshape(10,5)
calc_matrix = print(mat_4/mat_5)
calc_matrix

print("\n Linear combination : 3*A - 2*B \n",3*mat_4 - 2*mat_5)

[[1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]]

 Linear combination : 3*A - 2*B 
 [[8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]]


### Broadcasting

###### Broadcasting -- In NumPy, we can perform mathematical operations on arrays of different shapes. An array with a smaller shape is expanded to match the shape of a larger one. This is called broadcasting.

In [24]:
mat_6 = np.zeros((3,3))
print(mat_6)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
mat_7 = np.array([[1,2,3]])
row_added = mat_6 + mat_7
print(row_added)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [26]:
mat_8 = mat_7.T  # T for transpose, it alters the row and columns,vice-versa
print(mat_8)

[[1]
 [2]
 [3]]


In [27]:
# Creating table ndarray of shape 4 X 1 to broadcast across coloumn
mat_9 = np.array([[2,9,6,0]])
print(mat_9)
mat_9.T

[[2 9 6 0]]


array([[2],
       [9],
       [6],
       [0]])

In [30]:
# Doing broadcasting between 4 X 1 and 3 X 1 2D Arrays
braodcasted = mat_9 + mat_8  # floor division operation, 3 X 4 array created
print(braodcasted) 

[[ 3 10  7  1]
 [ 4 11  8  2]
 [ 5 12  9  3]]


In [29]:
# another broadcast
broadcasted_matrix = mat_6 + mat_8  # 3 X 3 and 3 X 1 matrices doing broadcasting
print(broadcasted_matrix)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


### Array Math

In [31]:
# Array Math
m1 = np.array(ri(11,30,20)).reshape(4,5)
m2 = np.array(ri(21,40,20)).reshape(4,5)

print("\n 1st Matrix of random single digit number\n---------------------------\n",m1)
print("\n 2nd Matrix of random single digit number\n---------------------------\n",m2)

print("\n Square root of 1st Matrix using np.sqrt()\n",'-'*50,"\n",np.sqrt(m1))
print("\n Square of 2nd Matrix using np.square()\n",'-'*50,"\n",np.square(m2))


 1st Matrix of random single digit number
---------------------------
 [[23 26 16 23 13]
 [14 25 16 13 14]
 [14 21 17 11 27]
 [13 17 25 13 13]]

 2nd Matrix of random single digit number
---------------------------
 [[32 37 37 35 39]
 [28 38 23 24 25]
 [21 35 30 30 37]
 [38 35 29 34 28]]

 Square root of 1st Matrix using np.sqrt()
 -------------------------------------------------- 
 [[4.79583152 5.09901951 4.         4.79583152 3.60555128]
 [3.74165739 5.         4.         3.60555128 3.74165739]
 [3.74165739 4.58257569 4.12310563 3.31662479 5.19615242]
 [3.60555128 4.12310563 5.         3.60555128 3.60555128]]

 Square of 2nd Matrix using np.square()
 -------------------------------------------------- 
 [[1024 1369 1369 1225 1521]
 [ 784 1444  529  576  625]
 [ 441 1225  900  900 1369]
 [1444 1225  841 1156  784]]
