### Import Numpy

In [2]:
import numpy as np

### Checking all functions within NumPy

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

### Applying NumPy Functions

In [5]:
np.sqrt(10)

3.1622776601683795

In [6]:
print("Minimnum Value: ",np.amin([23,89,90,100,99]))

Minimnum Value:  23


In [7]:
print("Maximum Value: ",np.amax([23,89,90,100,99]))

Maximum Value:  100


In [8]:
np.ceil(89.78)

90.0

In [15]:
print("After calculating square-root, rounding off to next value: ",np.ceil(np.sqrt(144.52)))

After calculating square-root, rounding off to next value:  13.0


In [18]:
print("After calculating square-root, rounding off to next value of each, and output the total: ",np.sum(np.ceil(np.sqrt([144,169,199]))))

After calculating square-root, rounding off to next value of each, and output the total:  40.0


##### List is used to collect items that usually consist of elements of multiple data types. An array is also a vital component that collects several items of the same data type. List cannot manage arithmetic operations. Array can manage arithmetic operations.

In [20]:
type(np.array)

builtin_function_or_method

In [19]:
np.array([78,90,12,45])

array([78, 90, 12, 45])

In [21]:
print(np.array([78,90,12,45]))

[78 90 12 45]


In [22]:
type(np.array([])) # one-dimentional array

numpy.ndarray

In [23]:
type(np.array([[]]))

numpy.ndarray

In [24]:
np.array([]).dtype # data-type of elements inside the ndarray or n-dimentional array --> default is 'float64'

dtype('float64')

In [25]:
# Conversion of data-type of array elements
np.array([],dtype=int)

array([], dtype=int32)

In [29]:
# copy a list to array
lst = [89,45,90,123,67.9,False,{'Name':"Sayantan", 'Gender':'Male', 'Age': 34}]
arr = np.array(lst)
print("Copied as list to an array --> ",arr)

# copy an array to another array --> as it is originally
array = np.asarray(arr)
print("Copied as array --> ",array)

Copied as list to an array -->  [89 45 90 123 67.9 False {'Name': 'Sayantan', 'Gender': 'Male', 'Age': 34}]
Copied as array -->  [89 45 90 123 67.9 False {'Name': 'Sayantan', 'Gender': 'Male', 'Age': 34}]


### ndarray as Matrix

In [30]:
my_matrix = [[12,23,34],[45,56,67],[78,89,91]]
matrix = np.array(my_matrix)
print("Type/Class of this Object : ",type(matrix))
print("Dimension of this Matrix : ",matrix.ndim) # ndim gives dimension, 2 for a matrix and 1 for vector(One Dimension)
print("Size of the Matrix : ",matrix.size) # size shows total number elements present in matrix
print("Shape of the Matrix : ",matrix.shape) # showing number of rows/columns
print("DataType of the Matrix ; ",matrix.dtype) # shows data-type of matrix

Type/Class of this Object :  <class 'numpy.ndarray'>
Dimension of this Matrix :  2
Size of the Matrix :  9
Shape of the Matrix :  (3, 3)
DataType of the Matrix ;  int32


In [33]:
a = np.arange(10) # arange is silimilar to list range method
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
b = np.arange(10.5,20.4,2) # arange method takes 3 arguments --> start/stop/step
print(b)

[10.5 12.5 14.5 16.5 18.5]


In [39]:
print("Every 5th number from 100 in reverse order \n",np.arange(100,-1,-5))

Every 5th number from 100 in reverse order 
 [100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15
  10   5   0]


In [46]:
print("Linearly Spaced 5 Numbers \n",'--'*15)
print(np.linspace(10,40,5))

Linearly Spaced 5 Numbers 
 ------------------------------
[10.  17.5 25.  32.5 40. ]


In [47]:
#Include end points and check space between the points
#By default endpoint=True
#Bydefaul retstep=False

# it will provide 4 numbers, 
# include the ending element, 
# and those will be equally sample numbers having steps in between

np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

### Matrix creation

In [57]:
print(np.zeros([10,10])) #using vector of zeroes

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
# using Vector of ones
print(np.ones([10,10]))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [60]:
# multiplying by any number to get it's own matrix
print(10*np.ones([10,10]))

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


In [71]:
# SEED method to manipulate the random output
np.random.seed(5) # Each seed number will generate similar data to every distinct notebook user
print("Random number generation , it uses Uniform Distribution technique")
print("--"*40)
print(np.random.rand(10,5))

Random number generation , it uses Uniform Distribution technique
--------------------------------------------------------------------------------
[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119]
 [0.61174386 0.76590786 0.51841799 0.2968005  0.18772123]
 [0.08074127 0.7384403  0.44130922 0.15830987 0.87993703]
 [0.27408646 0.41423502 0.29607993 0.62878791 0.57983781]
 [0.5999292  0.26581912 0.28468588 0.25358821 0.32756395]
 [0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309]
 [0.57766286 0.00164217 0.51547261 0.63979518 0.9856244 ]
 [0.2590976  0.80249689 0.87048309 0.92274961 0.00221421]
 [0.46948837 0.98146874 0.3989448  0.81373248 0.5464565 ]]


In [72]:
# random.randn() --> it does the random number generation using normal distribution technique i.e MEAN=0 & Std. Deviation=1
print(np.random.randn(10,5))

[[-0.08687561  1.56153229 -0.30585302 -0.47773142  0.10073819]
 [ 0.35543847  0.26961241  1.29196338  1.13934298  0.4944404 ]
 [-0.33633626 -0.10061435  1.41339802  0.22125412 -1.31077313]
 [-0.68956523 -0.57751323  1.15220477 -0.10716398  2.26010677]
 [ 0.65661947  0.12480683 -0.43570392  0.97217931 -0.24071114]
 [-0.82412345  0.56813272  0.01275832  1.18906073 -0.07359332]
 [-2.85968797  0.7893664  -1.87774088  1.53875615  1.82136474]
 [-0.42703139 -1.16470191 -1.39707402  0.87265462 -0.20211818]
 [-0.59835993 -0.2434197   2.08851469  0.34691933  0.74572695]
 [ 0.77690759  1.01842113  1.06135144 -0.71046645 -0.2151878 ]]


In [76]:
# printing vector(one dimentional) by using random.randint() random sampling method --> arguments passed are low(included)/high(excluded)/size
print("Random integer vector : ",np.random.randint(15,50,(10,5)))

Random integer vector :  [[45 15 43 23 29]
 [15 46 20 41 34]
 [43 26 34 18 38]
 [18 46 17 44 33]
 [22 15 16 45 42]
 [46 44 21 22 29]
 [24 22 40 41 46]
 [29 19 36 25 19]
 [47 32 18 30 32]
 [38 26 45 41 23]]


In [87]:
# A REAL TIME EXAMPLE OF RANDOM SAMPLING : OTP GENERATION METHOD
def otp_generation():
    otp = np.random.randint(1000,10000,1)
    print("Your Generated OTP is = ",otp)
    user_otp = int(input("Enter OTP Here: "))
    if otp == user_otp:
        print("Correct OTP! You are successfully logged in")
    else:
        print("Your OTP is Invalid! Enter A Valid OTP to LogIn")

In [88]:
otp_generation()

Your Generated OTP is =  [8193]
Enter OTP Here: 8193
Correct OTP! You are successfully logged in
